name: 'Pull from Lokalise'
description: GitHub action to download translation files from Lokalise TMS to your GitHub repository in the form of a pull request.
author: 'Lokalise Group, Ilya Krukowski'
inputs:
  api_token:
    description: 'API token for Lokalise with read/write permissions'
    required: true
    secret: true
  project_id:
    description: 'Project ID for Lokalise'
    required: true
  base_lang:
    description: 'Base language (e.g., en, fr_FR)'
    required: true
    default: 'en'
  translations_path:
    description: 'Paths to translation files'
    required: true
    default: |
      locales
  file_format:
    description: 'Format of the translation files (e.g., json). Find all supported file formats at https://developers.lokalise.com/reference/api-file-formats'
    required: true
    default: 'json'
  additional_params:
    description: 'Additional parameters for Lokalise CLI on pull. Find all supported options at https://github.com/lokalise/lokalise-cli-2-go/blob/main/docs/lokalise2_file_download.md'
    required: false
    default: ''
  temp_branch_prefix:
    description: 'Prefix for the temp branch to create pull request'
    required: false
    default: 'lok'
  always_pull_base:
    description: 'By default, changes in the base language translation files are ignored. Set this to true to include base language translations in the PR.'
    required: false
    default: false
  flat_naming:
    description: 'Use flat naming convention (true/false). If true, expects files like locales/en.json instead of locales/en/file.json'
    required: false
    default: false
  skip_include_tags:
    description: 'Skip setting the include-tags argument during download. This will download all translation keys for the specified format, regardless of tags.'
    required: false
    default: false
  pr_labels:
    description: 'Comma-separated list of labels to apply to the created pull request'
    required: false
    default: ''
  max_retries:
    description: 'Maximum number of retries on rate limit errors'
    required: false
    default: 3
  sleep_on_retry:
    description: 'Number of seconds to sleep before retrying'
    required: false
    default: 1
  download_timeout:
    description: 'Timeout for the download operation (in seconds)'
    default: 120
    required: false
permissions:
  contents: write
  pull-requests: write
branding:
  icon: 'download-cloud'
  color: 'orange'

outputs:
  created_branch:
    description: 'The branch that was created and used for the pull request'
    value: ${{ steps.create-commit.outputs.branch_name }}
  pr_created:
    description: 'A boolean value specifying whether the pull request with translation updates has been created'
    value: ${{ steps.check-pr-created.outputs.pr_created }}
  pr_number:
    description: 'Number of the created pull request'
    value: ${{ steps.create-update-pr.outputs.pr_number }}
  pr_id:
    description: 'ID of the created pull request'
    value: ${{ steps.create-update-pr.outputs.pr_id }}

runs:
  using: "composite"
  steps:
    - name: Install Lokalise CLIv2
      uses: bodrovis/install-lokalise-cli-v2@v1.0.2

    - name: Pull translation files from Lokalise
      id: pull-files
      shell: bash
      env:
        CLI_ADD_PARAMS: ${{ inputs.additional_params }}
        MAX_RETRIES: ${{ inputs.max_retries }}
        SLEEP_TIME: ${{ inputs.sleep_on_retry }}
        FILE_FORMAT: ${{ inputs.file_format }}
        TRANSLATIONS_PATH: "${{ inputs.translations_path }}"
        BASE_LANG: "${{ inputs.base_lang }}"
        ALWAYS_PULL_BASE: "${{ inputs.always_pull_base }}"
        FLAT_NAMING: "${{ inputs.flat_naming }}"
        DOWNLOAD_TIMEOUT: "${{ inputs.download_timeout }}"
        SKIP_INCLUDE_TAGS: "${{ inputs.skip_include_tags }}"
      run: |
        set -e
        
        CMD_PATH="${{ github.action_path }}/bin/lokalise_download"
        chmod +x "$CMD_PATH"
        "$CMD_PATH" "${{ inputs.project_id }}" "${{ inputs.api_token }}" || {
          echo "Error: lokalise_download script failed with exit code $?"
          exit 1
        }

        CMD_PATH="${{ github.action_path }}/bin/detect_changed_files"
        chmod +x "$CMD_PATH"
        "$CMD_PATH" || {
          echo "Error: detect_changed_files script failed with exit code $?"
          exit 1
        }

    - name: Commit changes
      id: create-commit
      if: steps.pull-files.outputs.has_changes == 'true'
      env:
        FILE_FORMAT: ${{ inputs.file_format }}
        TRANSLATIONS_PATH: "${{ inputs.translations_path }}"
        BASE_LANG: "${{ inputs.base_lang }}"
        ALWAYS_PULL_BASE: "${{ inputs.always_pull_base }}"
        FLAT_NAMING: "${{ inputs.flat_naming }}"
        TEMP_BRANCH_PREFIX: "${{ inputs.temp_branch_prefix }}"
      shell: bash
      run: |
        set -e

        CMD_PATH="${{ github.action_path }}/bin/commit_changes"
        chmod +x "$CMD_PATH"
        $("$CMD_PATH") || {
          echo "Error: commit_changes script failed with exit code $?"
          echo "has_changes=false" >> $GITHUB_OUTPUT
          exit 1
        }

    - name: Create or Update Pull Request
      if: steps.pull-files.outputs.has_changes == 'true' && steps.create-commit.outputs.commit_created == 'true'
      env:
        BRANCH_NAME: ${{ steps.create-commit.outputs.branch_name }}
        BASE_REF: ${{ github.ref_name }}
        PR_LABELS: ${{ inputs.pr_labels }}
      id: create-update-pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        result-encoding: string
        script: |
          const path = require('path');
          const createOrUpdatePR = require(path.join(process.env.GITHUB_ACTION_PATH, 'js/create-update-pr.js'));
          const result = await createOrUpdatePR({ github, context });
          core.setOutput('pr_created', result.created);
          core.setOutput('pr_number', result.pr.number);
          core.setOutput('pr_id', result.pr.id);
          return result.created;

    - name: Verify PR created
      id: check-pr-created
      shell: bash
      run: |
        if [ "${{ steps.create-update-pr.outputs.pr_created }}" != "true" ]; then
          echo "pr_created=false" >> $GITHUB_OUTPUT
        else
          echo "pr_created=true" >> $GITHUB_OUTPUT
        fi