package main

import (
	"reflect"
	"testing"
)

func TestEnvVarsToConfig(t *testing.T) {
	tests := []struct {
		name            string
		envVars         map[string]string
		expectedConfig  *Config
		expectError     bool
		expectedErrText string
	}{
		{
			name: "Valid environment variables",
			envVars: map[string]string{
				"BASE_REF":             "main",
				"HEAD_REF":             "refs/heads/feature/foo",
				"GITHUB_ACTOR":         "test_actor",
				"GITHUB_SHA":           "123456",
				"TEMP_BRANCH_PREFIX":   "temp",
				"TRANSLATIONS_PATH":    "translations",
				"FILE_FORMAT":          "json",
				"BASE_LANG":            "en",
				"FLAT_NAMING":          "true",
				"ALWAYS_PULL_BASE":     "false",
				"FORCE_PUSH":           "false",
				"GIT_USER_NAME":        "my_user",
				"GIT_USER_EMAIL":       "test@example.com",
				"OVERRIDE_BRANCH_NAME": "custom_branch",
				"GIT_COMMIT_MESSAGE":   "My commit msg",
			},
			expectedConfig: &Config{
				GitHubActor:        "test_actor",
				GitHubSHA:          "123456",
				BaseRef:            "main",
				HeadRef:            "feature/foo",
				TempBranchPrefix:   "temp",
				FileExt:            []string{"json"},
				BaseLang:           "en",
				FlatNaming:         true,
				AlwaysPullBase:     false,
				GitUserName:        "my_user",
				GitUserEmail:       "test@example.com",
				OverrideBranchName: "custom_branch",
				GitCommitMessage:   "My commit msg",
				TranslationPaths:   []string{"translations"},
				ForcePush:          false,
			},
			expectError: false,
		},
		{
			name: "FILE_EXT normalization and dedupe",
			envVars: map[string]string{
				"BASE_REF":           "main",
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_EXT":           "\n .JSON \n  yaml  \n .json \n",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "false",
				"ALWAYS_PULL_BASE":   "true",
				"FORCE_PUSH":         "false",
			},
			expectedConfig: &Config{
				GitHubActor:      "test_actor",
				GitHubSHA:        "123456",
				BaseRef:          "main",
				TempBranchPrefix: "temp",
				FileExt:          []string{"json", "yaml"},
				BaseLang:         "en",
				FlatNaming:       false,
				AlwaysPullBase:   true,
				GitCommitMessage: "Translations update",
				TranslationPaths: []string{"translations"},
				ForcePush:        false,
			},
			expectError: false,
		},
		{
			name: "Empty commit msg",
			envVars: map[string]string{
				"GITHUB_ACTOR":         "test_actor",
				"GITHUB_SHA":           "123456",
				"BASE_REF":             "main",
				"TEMP_BRANCH_PREFIX":   "temp",
				"TRANSLATIONS_PATH":    "translations",
				"FILE_FORMAT":          "json",
				"BASE_LANG":            "en",
				"FLAT_NAMING":          "true",
				"ALWAYS_PULL_BASE":     "false",
				"FORCE_PUSH":           "false",
				"GIT_USER_NAME":        "my_user",
				"GIT_USER_EMAIL":       "test@example.com",
				"OVERRIDE_BRANCH_NAME": "custom_branch",
			},
			expectedConfig: &Config{
				GitHubActor:        "test_actor",
				GitHubSHA:          "123456",
				BaseRef:            "main",
				TempBranchPrefix:   "temp",
				FileExt:            []string{"json"},
				BaseLang:           "en",
				FlatNaming:         true,
				AlwaysPullBase:     false,
				GitUserName:        "my_user",
				GitUserEmail:       "test@example.com",
				OverrideBranchName: "custom_branch",
				GitCommitMessage:   "Translations update",
				TranslationPaths:   []string{"translations"},
				ForcePush:          false,
			},
			expectError: false,
		},
		{
			name: "FILE_EXT has precedence over FILE_FORMAT",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "structured_json",
				"FILE_EXT":           "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectedConfig: &Config{
				GitHubActor:      "test_actor",
				GitHubSHA:        "123456",
				BaseRef:          "main",
				TempBranchPrefix: "temp",
				FileExt:          []string{"json"},
				BaseLang:         "en",
				FlatNaming:       true,
				AlwaysPullBase:   false,
				GitCommitMessage: "Translations update",
				TranslationPaths: []string{"translations"},
				ForcePush:        false,
			},
			expectError: false,
		},
		{
			name: "Missing required environment variable",
			envVars: map[string]string{
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
			},
			expectError:     true,
			expectedErrText: "GITHUB_ACTOR",
		},
		{
			name: "Missing required extension and format info",
			envVars: map[string]string{
				"GITHUB_SHA":         "123456",
				"GITHUB_ACTOR":       "test_actor",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "cannot infer file extension",
		},
		{
			name: "Invalid boolean environment variable",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "not_a_bool",
				"ALWAYS_PULL_BASE":   "true",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "FLAT_NAMING",
		},
		{
			name: "FILE_EXT multiple values",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations\nlocales",
				"FILE_EXT":           "strings\nstringsdict",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "false",
				"ALWAYS_PULL_BASE":   "true",
				"FORCE_PUSH":         "false",
			},
			expectedConfig: &Config{
				GitHubActor:      "test_actor",
				GitHubSHA:        "123456",
				BaseRef:          "main",
				TempBranchPrefix: "temp",
				FileExt:          []string{"strings", "stringsdict"},
				BaseLang:         "en",
				FlatNaming:       false,
				AlwaysPullBase:   true,
				GitCommitMessage: "Translations update",
				TranslationPaths: []string{"translations", "locales"},
				ForcePush:        false,
			},
			expectError: false,
		},
		{
			name: "GIT_SIGN_COMMITS true is respected",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
				"GIT_SIGN_COMMITS":   "true",
			},
			expectedConfig: &Config{
				GitHubActor:      "test_actor",
				GitHubSHA:        "123456",
				BaseRef:          "main",
				TempBranchPrefix: "temp",
				FileExt:          []string{"json"},
				BaseLang:         "en",
				FlatNaming:       true,
				AlwaysPullBase:   false,
				GitCommitMessage: "Translations update",
				GitSignCommits:   true,
				TranslationPaths: []string{"translations"},
				ForcePush:        false,
			},
			expectError: false,
		},
		{
			name: "invalid GIT_SIGN_COMMITS falls back to false",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
				"GIT_SIGN_COMMITS":   "wat",
			},
			expectedConfig: &Config{
				GitHubActor:      "test_actor",
				GitHubSHA:        "123456",
				BaseRef:          "main",
				TempBranchPrefix: "temp",
				FileExt:          []string{"json"},
				BaseLang:         "en",
				FlatNaming:       true,
				AlwaysPullBase:   false,
				GitCommitMessage: "Translations update",
				GitSignCommits:   false,
				TranslationPaths: []string{"translations"},
				ForcePush:        false,
			},
			expectError: false,
		},
		{
			name: "invalid ALWAYS_PULL_BASE",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "not_a_bool",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "ALWAYS_PULL_BASE",
		},
		{
			name: "invalid FORCE_PUSH",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "not_a_bool",
			},
			expectError:     true,
			expectedErrText: "FORCE_PUSH",
		},
		{
			name: "missing BASE_LANG",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "BASE_LANG",
		},
		{
			name: "BASE_LANG with spaces is rejected",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "  ",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "BASE_LANG environment variable is required",
		},
		{
			name: "BASE_LANG with slash is rejected",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en/us",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "BASE_LANG must not contain path separators",
		},
		{
			name: "BASE_LANG with backslash is rejected",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          `en\us`,
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "BASE_LANG must not contain path separators",
		},
		{
			name: "FILE_EXT with slash is rejected",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_EXT":           "json/foo",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: `invalid file extension "json/foo"`,
		},
		{
			name: "FILE_EXT with backslash is rejected",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_EXT":           `json\foo`,
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "invalid file extension \"json\\\\foo\"",
		},
		{
			name: "no valid extensions after normalization",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_EXT":           " \n . \n\t",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "no valid file extensions after normalization",
		},
		{
			name: "refs heads prefix is stripped and whitespace trimmed",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           " refs/heads/main ",
				"HEAD_REF":           " refs/heads/feature/foo ",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectedConfig: &Config{
				GitHubActor:      "test_actor",
				GitHubSHA:        "123456",
				BaseRef:          "main",
				HeadRef:          "feature/foo",
				TempBranchPrefix: "temp",
				FileExt:          []string{"json"},
				BaseLang:         "en",
				FlatNaming:       true,
				AlwaysPullBase:   false,
				GitCommitMessage: "Translations update",
				TranslationPaths: []string{"translations"},
				ForcePush:        false,
			},
			expectError: false,
		},
		{
			name: "invalid translation path bubbles up",
			envVars: map[string]string{
				"GITHUB_ACTOR":       "test_actor",
				"GITHUB_SHA":         "123456",
				"BASE_REF":           "main",
				"TEMP_BRANCH_PREFIX": "temp",
				"TRANSLATIONS_PATH":  "../translations",
				"FILE_FORMAT":        "json",
				"BASE_LANG":          "en",
				"FLAT_NAMING":        "true",
				"ALWAYS_PULL_BASE":   "false",
				"FORCE_PUSH":         "false",
			},
			expectError:     true,
			expectedErrText: "escapes repo root",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// scrub env so CI-provided vars don't bleed into tests
			allEnvVars := []string{
				"GITHUB_ACTOR",
				"GITHUB_SHA",
				"BASE_REF",
				"HEAD_REF",
				"TEMP_BRANCH_PREFIX",
				"TRANSLATIONS_PATH",
				"BASE_LANG",
				"FLAT_NAMING",
				"ALWAYS_PULL_BASE",
				"FORCE_PUSH",
				"GIT_USER_NAME",
				"GIT_USER_EMAIL",
				"OVERRIDE_BRANCH_NAME",
				"GIT_COMMIT_MESSAGE",
				"FILE_FORMAT",
				"FILE_EXT",
				"GIT_SIGN_COMMITS",
			}
			for _, k := range allEnvVars {
				t.Setenv(k, "")
			}

			for key, value := range tt.envVars {
				t.Setenv(key, value)
			}

			config, err := envVarsToConfig()

			if tt.expectError {
				if err == nil {
					t.Fatalf("Expected error but got nil")
				}
				if tt.expectedErrText != "" && !containsSubstring(err.Error(), tt.expectedErrText) {
					t.Fatalf("Expected error containing '%s', but got '%v'", tt.expectedErrText, err)
				}
				return
			}

			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			if config == nil {
				t.Fatalf("Expected config but got nil")
			}
			if !reflect.DeepEqual(config, tt.expectedConfig) {
				t.Fatalf("Expected config %+v but got %+v", *tt.expectedConfig, *config)
			}
		})
	}
}
